name: CT
favicon: null
layout_spectrum: 0.8508396439719945
typography_spectrum: 0.4401131693739444
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3536089521367103
  lightness: 0.5866724769584835
  saturation: 0.3180774359498173
  rhythmicContrast: 0.2467812409158796
purpose: []
