name: CT
favicon: null
layout_spectrum: 0.5739
typography_spectrum: 0.59729
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#60ba04'
    - '#13b6eb'
    - '#fefefe'
    - '#000000'
    - '#008000'
  brandStrength: 1
  lightness: 0.5866724769584835
  saturation: 0.3180774359498173
  rhythmicContrast: 0.2467812409158796
purpose: []
